name: bk_tree
description: A Dart BK-Tree implementation for efficient nearest neighbor searches using Hamming distance, optimized for bulk file hash processing and duplicate detection.
version: 0.1.1
# 详细描述 (显示在pub.dev详情页)  
repository: https://github.com/RequieMa/bk_tree
license: BSD-3-Clause
documentation: https://pub.dev/documentation/bk_tree
issue_tracker: https://github.com/RequieMa/bk_tree/issues

environment:
  sdk: ^3.6.0

dependencies:
  path: ^1.8.0
  logging: ^1.3.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics: # 最多5个标签
  - data-structures
  - dart
